modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/OldJavaWarning"

[[mods]]
modId="oldjavawarning"
updateJSONURL="https://updates.blamejared.com/get?n=oldjavawarning&gv=1.16.1"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.oldjavawarning]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.oldjavawarning]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="CLIENT"